# Generated by Django 3.0.6 on 2020-07-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20200717_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='person',
            field=models.ManyToManyField(to='my_app.Customer'),
        ),
    ]
