# Generated by Django 3.0.6 on 2020-07-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_individual_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='person',
        ),
        migrations.AddField(
            model_name='individual',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='balence',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='fullname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='individual',
            name='mobile',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
