# Generated by Django 3.0.6 on 2020-07-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20200718_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='Total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='product',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
